baseURL = 'http://nyble.blog'
languageCode = 'en-us'
title = 'Nyble'
theme = 'terminal'

[params]
    contentTypeName = "posts"
    themeColor = "green"
    showMenuItems = 1
    fullWidthTheme = false
    centerTheme = true

[languages]
    [languages.en]
        title = "Nyble"
        subtitle = "A development blog covering a bunch of different topics"
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
            logoText = "Nyble"
            logoHomeLink = "/nyble"

        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "author"
                name = "Author"
                url = "/author"