baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Learning to Learn'

[params]
    contentTypeName = "posts"
    themeColor = "green"
    showMenuItems = 1
    fullWidthTheme = false
    centerTheme = true

[languages]
    [languages.en]
        title = "Learning to Learn"
        subtitle = "A development blog covering a bunch of different topics"
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
            logoText = "Learning to Learn"
            logoHomeLink = "/"

        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "about"
                name = "About"
                url = "/about"